apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-ns.yaml
- 01-deployment.yaml
- 02-service.yaml
namespace: prueba-create
images:
- name: gcr.io/google-samples/hello-app
  newName: gcr.io/google-samples/hello-app
  newTag: 1.0

